name: Test Meraki FW Rule Format

on:
  workflow_dispatch:

jobs:
  test_format:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch FW Rules
        env:
          MERAKI_API_KEY: ${{ secrets.MERAKI_API_KEY }}
          MERAKI_NETWORK_ID: ${{ secrets.MERAKI_NETWORK_ID }}
        shell: python
        run: |
          import os, requests, json

          API_KEY = os.environ["MERAKI_API_KEY"]
          NETWORK_ID = os.environ["MERAKI_NETWORK_ID"]

          headers = {
              "X-Cisco-Meraki-API-Key": API_KEY,
              "Content-Type": "application/json"
          }

          url = f"https://api.meraki.com/api/v1/networks/{NETWORK_ID}/appliance/firewall/l3FirewallRules"
          r = requests.get(url, headers=headers)
          
          print("--- RESPONSE FROM MERAKI ---")
          print(json.dumps(r.json(), indent=2))
